version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
    environment:
      DB_DRIVER: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: sample_db
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./front/:/app:delegated
      - node_modules:/app/node_modules
      - next:/app/.next
    ports:
      - "3000:3000"
    depends_on:
      - api
  db:
    image: mysql:5.7
    command: mysqld
    volumes:
      - db:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306

volumes:
  node_modules:
    driver: local
  next:
    driver: local
  db:
    driver: local
