version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./front/:/app:delegated
      - node_modules:/app/node_modules
      - next:/app/.next
    ports:
      - "3001:3000"
    depends_on:
      - api

volumes:
  node_modules:
    driver: local
  next:
    driver: local
